[package]
name = "palantir"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[[bin]]
name = "palantir"
path = "src/main.rs"

[dependencies]
ebpf-common = { workspace = true, features = ["std"] }
ip-metadata = { workspace = true }

aya = { workspace = true }
aya-log = { workspace = true }

axum = { workspace = true, features = ["http1", "http2", "tokio", "tracing", "json"]}
async-stream = { workspace = true }
futures-util = { workspace = true }
tower-http = { workspace = true, features = ["cors"] }

libc = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "net", "sync", "time"] }
log = { workspace = true }
env_logger = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
maxminddb = { workspace = true, features = ["mmap"] }

[build-dependencies]
aya-build = { workspace = true }
cargo_metadata = { workspace = true }
